### ISSUE TITLE
No callback for setting mediaURL

### ISSUE THREAD

**Issue by nsarno-lucid** [DATechnologies/VelociPlayer#13]
I would like to set a new mediaURL and then immediately seek to a time based on the new media's duration. However, the duration sets asynchronously (within the didSet of mediaURL) and therefore seeking doesn't work immediately.  

Attempt 1:
```
        // Fails bc duration == 0
        self.player.mediaURL = url
        let duration = player.duration.seconds
        let seconds = 0.3 * duration
        self.player.seek(to: VPTime(seconds: seconds, preferredTimescale: 1))
        self.player.play()
```

Attempt 2:
```
        // Fails within seek(toPercent:) function bc duration == 0
        self.player.mediaURL = url
        self.player.seek(toPercent: 0.3)
        self.player.play()
```

One idea would be to not set mediaURL directly and instead have a function similar to the initializer.

```
func updateMedia(autoPlay: Bool, mediaURL: URL?, startTime: VPTime?)
``` 

Otherwise, maybe some sort of callback when setting new mediaURL to signify "didFinishSetting"

**Comment by EthanTheInnovator** [comment]
As of version 3.0.0, you can set the `startTime` on the player to begin playback at a specific time. It may be a good idea to have a function like that in the future to simplify the call site, but you should be able to achieve this functionality by setting the `startTime` _before_ setting the `mediaURL`
